composition:
  modules:
    - name: ConsoleWriter
      assembly: GenericHostConsole.Writer
      configurationSection: consolewriterConfiguration
      optional: true

logging:
  logLevel:
    Default: Debug
    Microsoft: Debug

consolewriterConfiguration:
  writeIntervalInSeconds: 2